### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by whimsicaldreamer** [tovic/parsedown-extra-plugin#2]
Firstly, a great plugin to parsedown specially after the new commit.
On using it, it struck to me what about if the image links were made to be clickable, if the user chose to?

**Comment by tovic** [comment]
What do you mean by clickable? An ability to make all images becomes wrapped by an anchor element?

**Comment by whimsicaldreamer** [comment]
not all images. Only those are done by `![image](http://link)` and that too if the user wants.

**Comment by tovic** [comment]
Then how can we specify things to decide that an image should be clickable?

**Comment by tovic** [comment]
Try something like this:

~~~ .php
$parser->images_attr = array(
    'onclick' => 'window.open(this.src);'
);
~~~

**Comment by whimsicaldreamer** [comment]
This is what I had used, but did'nt work.
```
		$this->Parsedown->images_attr = array(
			'class' => 'link_image',
			'onClick' => 'window.open(this.src);'
		);
```

**Comment by whimsicaldreamer** [comment]
Pretty nice. But will it be secure adding `onClick` rather than anchor tags? I dont know much about XSS so am curious.

**Comment by tovic** [comment]
For that `onclick` example, is now depends on the `src` content. Try this markup:

~~~ .markdown
![test](data:text/html,<script>alert('fail');</script>)
~~~

If it opens up a new tab with an alert contains `fail` then it is not safe.

**Comment by whimsicaldreamer** [comment]
It survives the test. :smile:

**Comment by tovic** [comment]
What about:

~~~ markdown
![test](data:text/html,%3Cscript%3Ealert('fail');%3C%2Fscript%3E)
~~~
