### ISSUE TITLE
Could you provide some test for all the supported cases?

### ISSUE THREAD

**Issue by karfau** [tovic/parsedown-extra-plugin#3]
You have a lot of cases in your README.md,
how did you verify they all work?

I can help with setting up test automation but don't have enough experience in testing with PHP myself to build those tests. 

Ideally you could use the tests to create a report with all the supported usecases?

Best Christian

**Comment by tovic** [comment]
Is creating a `test` folder contains some of the required code snippets _manually_ can be considered a test? If so, I can create them.

**Comment by karfau** [comment]
Well my personal opinion is that it is only a test when I can clone the project, do some documented setup maybe and run the tests and the pass or fail, aka are executable.

But if you also don't know how to achieve this, maybe the snippets for input and expected output are a good starting point.

Then it might be easier for somebody who knows or is willing to learn how to do it, to contribute.

I just imagine that some projects would love to include those features you offer, but might not consider it, because there is no easy proof that future changes will not break everything.

Best Christian
