### ISSUE TITLE
Incorrect parsing of links when using advanced attributes with underscores like target

### ISSUE THREAD

**Issue by aresdr** [tovic/parsedown-extra-plugin#4]
Hi,

I recently installed this plugin on my current dev project, and I noticed the next things:

```
_[text](https://www.example.com/){target='_blank'}_
Outputs:
_<a href="https://www.example.com/" target="_blank">text</a>_
```
```

__[text](https://www.example.com/){target='_blank'}__
Outputs:
__<a href="https://www.example.com/" target="_blank">text</a>__
```

But:
```
[text](https://www.example.com/){target='blank'}
Outputs:
<em><a href="https://www.example.com/" target="blank">text</a></em>
```

So there must be an alternative to escape _blank, I tried using the HTML entity 95 but once it gets saved on my application it is converted again to _, so the second save will throw back the problem.

Thanks.

**Comment by tovic** [comment]
Thanks for the report. What&rsquo;s the expected result you want?

**Comment by aresdr** [comment]
The point is I can't use target='_blank' in a link that is bold or italic. Maybe a filter would be good where target='blank' print target='_blank' automatically or something like that.

Thanks.

**Comment by tovic** [comment]
Is there a reason that the `<strong>` and/or `<em>` tags should be outside the anchor? Because you can do this instead:

~~~ .markdown
[_some text_](http://example.com) {target="_blank"}
~~~
